# Generated by Django 4.2.11 on 2024-04-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_courseuser_usercourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='user',
            new_name='user_id',
        ),
    ]
