# Generated by Django 4.2.11 on 2024-04-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_user_usercourse_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
